GeAsis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import ModelTracker
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Web.urls',namespace="Web")),
    path('track/', include('ModelTracker.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
app_name="Web"

Web/urls.py
from django.urls import include, path

from .views import * 
app_name = 'Web'
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("home", IndexView.as_view(),name="home" ),
    path("", LoginView.as_view(),name="login" ),
    path('logout/',LogoutView.as_view(next_page="/"),name="logout"),
    path('users/',UserListView.as_view(),name="usuarios"),

    path("users/create/",UsuarioCreateView.as_view(),name="create_user"),
    path("users/edit/<int:pk>/",UsuarioUpdateView.as_view(),name="edit_user"),
    path('Usuario/changepassword/<int:pk>/', UsuarioUpdatePasswordView.as_view(), name='UsuarioChangePassword'),
    path('Usuario/reset/<int:pk>/', UsuarioResetPasswordView, name='UsuarioResetPassword'),
    path('Usuario/activate/<int:pk>/', UsuarioActivate, name='UsuarioActivate   '),
    path('Usuario/desactivate/<int:pk>/', UsuarioDesactivate, name='UsuarioDesactivate'),
    path('import/', run, name='inportEESS'),
    path('EESS/', EstablecimientoListView.as_view() ,name='establecimientos'),
    path('programacion/', ProgramacionListView.as_view() ,name='programaciones'),
    path('liquidacion/', LiquidacionListView.as_view() ,name='liquidaciones'),
    path('mantenimiento-variables/', MantenimientoVariablesListView.as_view() ,name='mantenimiento-variables'),
    path('mantenimiento-EESS/', MantenimientoEESSListView.as_view() ,name='mantenimiento-EESS'),
    path('importacion-INFORHUS/', ImportacionBaseListView.as_view() ,name='inforhus')

]

templates/Seguridad/usuario.html
  {% extends 'base.html' %}


  {% load i18n %}
 {% block  configuracion %}menu-is-opening menu-open"{% endblock %} 
 {% block usuarios %}active{% endblock %}
  {% block content %}
  <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css">
  <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

  <div class="container-fluid">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <div class="row align-items-center">
          <div class="col-lg-3">
            <h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-list"></i> Crear Usuarios</h6>
          </div>

        </div>

      </div>
      <div class="card-body">

        <form method="post" id="formUsuario" action="{% url 'Web:create_user' %}" class="needs-validation" novalidate
          enctype="multipart/form-data">



          <div class="module aligned">
            {% csrf_token %}
 
            <div class="row">
                <div class="form-group col-lg-4">
                  <label for="id_persona" class="form-label">Persona</label>
                  <select name="persona" id="id_persona">
                  <option value="">Seleccione..</option>
                  {% for i in  persona %}
                    <option value="{{i.id}}">{{i.nombres}} {{i.apellidos}}</option>
                  {% endfor %}
                  </select>
                  <div class="invalid-feedback" id="invalid_persona">Este campo es requerido.</div>
                </div>
        
           
            </div>

            {% if error %}
            <div class="alert alert-danger text-center" role="alert">
              {% for field, error in error.items %}
              {{ error | striptags }}
              <br>
              {% endfor %}
            </div>
            {% endif %}

            <div class="row field-permissions">


              <div>


                <label for="id_permissions">Permisos:</label>

                <div class="related-widget-wrapper">



                  {{form.groups}}


                </div>

              </div>

            </div>

            <a class="btn btn-ligth" href="{% url 'Web:usuarios' %}">Volver</a>
            <button type="button" id="btn-add-usuario" class="btn btn-primary">Guardar usuario</button>
          </div>
        </form>
      </div>
    </div>



    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/SelectBox.js"></script>
    <script type="text/javascript" src="/static/admin/js/SelectFilter2.js"></script>

  </div>


  {% endblock content %}

  {% block js_page %}
  <script>
    $(document).ready(function () {
      let persona=document.getElementById("id_persona")
      
      document.getElementById("btn-add-usuario").addEventListener("click", function (e) {
        persona.classList.remove("is-invalid")

        let error=0
        e.preventDefault()
        if (document.getElementById("invalid_group") != null) {
          document.getElementById("invalid_group").innerHTML = ""

        }
        if (persona.value=="") {
          error=1
          persona.classList.add("is-invalid")
          document.getElementById("invalid_persona").innerHTML="Este campo es requerido."
        }
        let form = document.querySelector("#formUsuario")
        let url = document.getElementById("formUsuario").getAttribute("action")

        let formData = new FormData(form)
        var sel = document.querySelector("#id_groups_to");
        console.log(sel.options)
        sel.classList.remove("is-invalid", "form-select")

        for (var i = 0, n = sel.options.length; i < n; i++) { // looping over the options
          if (sel.options[i].value) {
            formData.append("groups", (sel.options[i].value))
          } else {

          }

        }

        if (error==0) {
          fetch(url, {
          method: "POST",

          body: formData
        }).then(data => data.json()).then(response => {
          console.log(response);
          if (response.status == 500) {
            notificacion(1500, "Error", "error", "Revise los campos")
           
            if (response.form.groups) {
              let div = document.createElement("div")
              div.classList.add("invalid-feedback")
              div.setAttribute("id", "invalid_group")
              div.innerHTML = response.form.groups[0]
              sel.after(div)
              sel.classList.add("is-invalid", "form-select")

            }
          } else {
            Swal.fire({
              title: 'Éxito!',
              text: "Usuario guardado!",
              icon: 'success',
              confirmButtonColor: '#3085d6',

              confirmButtonText: 'Ok!'
            }).then((result) => {
              if (result.isConfirmed) {
                window.location.href = response.url
              }
            })
          }
        })
        }
      })
    })
  </script>

  {% endblock js_page %}

templates/Seguridad/usuarioChangePassword.html
<div class="">
<br>
    <form class="needs-validation" action="{% url 'Web:UsuarioChangePassword' usuario.pk %}" method="post">
        {% load static %}
    
        {% csrf_token %}
        <div class="col">
            <div class="form-outline">
                            <label for="id_password1" class="form-label">Nueva Contraseña</label>

                <input type="password" name="new_password1" autocomplete="new-password" class="form-control" required=""
                id="id_new_password1">           
                <div class="invalid-feedback" id="invalid_new_password1"></div>
    
              </div>
          
        </div>
        <br>
        <div class="col mb-4">
            <div class="form-outline">
                            <label for="id_password1" class="form-label">Repetir Contraseña</label>

                <input type="password" name="new_password2" autocomplete="new-password2" class="form-control" required=""
                id="id_new_password2">
                <div class="invalid-feedback" id="invalid_new_password2"></div>
    
              </div>
           
        </div>
    
    
        <button type="submit" class="btn btn-primary" id="btnEditUser" style="display:none">Submit</button>
    </form>

</div>
{% block js_page %}
<script>
    $("#btnEditUser").on("click", function (e) {

        var id = $("#id").val()
        let password = document.getElementById("id_new_password1")
        let password2 = document.getElementById("id_new_password2")
        var paramaters = new FormData($('.needs-validation')[0])
        console.log($(".needs-validation").attr("action"));
        $.ajax({
            type: "POST",
            url: $(".needs-validation").attr("action"),
            data: paramaters,
            dataType: "json",
            processData: false, // tell jQuery not to process the data
            contentType: false,
            success: function (response) {
                console.log(response);
                if (response.status == 200) {
                    de.close()
                    notificacion(1500, "Genial!", "success", "Contraseña actualizada!")
                } else {
                    if (response.form.new_password1) {
                        if (response.form.new_password1.length > 1) {
                            console.log("if")
                            let errors = ""
                            if (response.form.new_password1.length > 2) {
                                document.getElementById("invalid_password1").parentNode.parentNode
                                    .classList.add("mb-4")
                                password2.value = ""
                            }
                            for (let i = 0; i < response.form.new_password1.length; i++) {
                                errors += `${response.form.new_password1[i]}\n`

                            }
                            document.getElementById("invalid_new_password1").innerHTML = errors
                            password.classList.add("is-invalid")

                        } else {
                            console.log("else");

                            document.getElementById("invalid_new_password1").innerHTML = response
                                .form
                                .new_password1[0]
                            password.classList.add("is-invalid")
                            password.value = ""
                            password2.value = ""

                        }

                    }
                    if (response.form.new_password2) {
                        document.getElementById("invalid_new_password2").innerHTML = response.form
                            .new_password2[0]
                        password2.classList.add("is-invalid")
                        password2.value = ""
                        password.value = ""

                    }
                }
            }
        }).done(function (data) {}).fail(function (jqXHR, textStatus, errorThrown) {
            alert("done:" + textStatus + ': ' + errorThrown);
        }).always(function (data) {

        });;
        return false;
    });
    
</script>

{% endblock js_page %}

templates/Seguridad/usuarioedit.html
 {% extends 'base.html' %}
 {% block  configuracion %}menu-is-opening menu-open"{% endblock %} 
 {% block usuarios %}active{% endblock %}

    {% block content %}
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">

    <div class="container-fluid">
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <div class="row align-items-center">
            <div class="col-lg-3">
              <h6 class="m-0 font-weight-bold text-primary"><i class="fa fa-list"></i> Editar Usuarios</h6>
            </div>

          </div>

        </div>
        <div class="card-body">
        
          <form method="post" id="formUsuario" action="{% url 'Web:edit_user' usuario.pk %}" class="needs-validation" novalidate
            enctype="multipart/form-data">
            <div class="module aligned">
              {% csrf_token %}
               <div class="row mb-4">
                 <div class="col-lg-6">
                <div class="form-outline">
                                  <label class="form-label" for="id_username">Usuario</label>

                  <input type="text" name="username" value="{% if usuario %}{{usuario.username}}{% endif %}" id="id_username" class="form-control" >
                    <div class="invalid-feedback" id="invalid_username">Este campo es requerido.</div>

                </div>
              </div>
  
            </div>
        
        
              {% if error %}
              <div class="alert alert-danger text-center" role="alert">
                {% for field, error in error.items %}
                {{ error | striptags }}
                <br>
                {% endfor %}
              </div>
              {% endif %}

              <div class="form-row field-permissions">


                <div>


                  <label for="id_permissions">Permisos:</label>

                  <div class="related-widget-wrapper">



                    {{form.groups}}


                  </div>

                </div>

              </div>

              <a class="btn btn-ligth" href="{% url 'Web:usuarios' %}">Volver</a>
              <button type="button" id="btn-add-usuario" 
                class="btn btn-primary">Guardar usuario</button>
            </div>
          </form>
        </div>
      </div>



      <script type="text/javascript" src="/admin/jsi18n/"></script>
      <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
      <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
      <script type="text/javascript" src="/static/admin/js/core.js"></script>
      <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
      <script type="text/javascript" src="/static/admin/js/SelectBox.js"></script>
      <script type="text/javascript" src="/static/admin/js/actions.js"></script>
      <script type="text/javascript" src="/static/admin/js/SelectFilter2.js"></script>
      <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
      <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
      <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    </div>


    {% endblock content %}

    {% block js_page %}
    <script>
      $(document).ready(function () {
              const removeElements = (elms) => elms.forEach(el => el.remove());

               let username = document.getElementById("id_username")


        username.addEventListener("keyup", function () {
          username.classList.remove("is-invalid")
        })
   
        document.getElementById("btn-add-usuario").addEventListener("click", function (e) {
                removeElements(document.querySelectorAll(".invalid-feedback"));
          console.log(document.querySelectorAll(".invalid_group"))
          e.preventDefault()
          let error=0
          if (  document.getElementById("invalid_group")!=null) {
            document.getElementById("invalid_group").innerHTML=""

          }
          let form = document.querySelector("#formUsuario")
          let url = document.getElementById("formUsuario").getAttribute("action")

          let formData = new FormData(form)
          var sel = document.querySelector("#id_groups_to");
          sel.classList.remove("is-invalid","form-select")
          if(sel.options.length>1){
              let div=document.createElement("div")
                div.classList.add("invalid-feedback")
                div.setAttribute("id","invalid_group")
                div.innerHTML="Escoga solo un Perfil"
                sel.after(div)
                sel.classList.add("is-invalid","form-select")
              error=1
          }   

          for (var i = 0, n = sel.options.length; i < n; i++) { // looping over the options
            if (sel.options[i].value){
              formData.append("groups", (sel.options[i].value))
            }else{
              
            }

          }
          if(error==0){
            
          fetch(url, {
            method: "POST",

            body: formData
          }).then(data => data.json()).then(response => {
              console.log(response)
            if (response.status == 500) {
              notificacion(1500,"Error","error","Revise los campos")

           
              if (response.form.username) {
                document.getElementById("invalid_username").innerHTML = response.form.username[0]
                username.classList.add("is-invalid")

              }
  
            
              if (response.form.groups) {
                let div=document.createElement("div")
                div.classList.add("invalid-feedback")
                div.setAttribute("id","invalid_group")
                div.innerHTML= response.form.groups[0]
                sel.after(div)
                sel.classList.add("is-invalid","form-select")

              }
            } else {
              Swal.fire({
                title: 'Éxito!',
                text: "Usuario editado!",
                icon: 'success',
                confirmButtonColor: '#3085d6',
                allowOutsideClick:false,

                confirmButtonText: 'Ok!'
              }).then((result) => {
                if (result.isConfirmed) {
                  window.location.href = response.url
                }
              })
            }
          })
          }
        })
      })
    </script>

    {% endblock js_page %}

templates/Seguridad/usuarios.html
{% extends "base.html" %}
 {% block  configuracion %}menu-is-opening menu-open"{% endblock %} 
 {% block usuarios %}active{% endblock %}
{% comment %} {% block navusuario %}nav-item active{% endblock  %}
{% block collapseUsuarios %}collapse show{% endblock  %}
{% block usuario_list %}collapse-item active{% endblock  %} {% endcomment %}
{% load static %}
{% block content %}


  <div class="card shadow">
    <!-- Card Header - Dropdown -->
    <div class=" card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold ">Listado de Usuarios</h6>
      <a class="btn btn-primary " href="{% url 'Web:create_user' %}"><i class="fa fa-plus-circle "></i>&nbsp;Nuevo usuario</a>
    </div>
    <!-- Card Body -->
    <div class="card-body ">
<div class="table-responsive">

            <table class="table  table-hover  dt-responsive" id="TablaUsuarios" style="width: 100%;">
        <thead>
          <tr>
            <th  style="width: 5%;"class="all">Id</th>
            <th style="width: 15%;">Nombres</th>
            <th style="width: 10%;">Usuario</th>
            <th style="width: 15%;">Fecha Creación</th>
            <th style="width: 10%;">Rol</th>
            <th style="width: 10%;">Estado</th>
            <th style="width: 30%;">Opciones</th>
          </tr>
        </thead>



      </table>
      </div>
    </div>
  </div>

{% endblock content %}
{% block js_page %}

<script>
 var TablaUsuarios
  $(document).ready(function () {

    TablaUsuarios = $("#TablaUsuarios").DataTable({
      responsive: true,
      processing:true,
      ordering:false,
      ajax: {
        url: "{% url 'Web:usuarios' %}",
        type: "POST",
        data: {
          "action": "searchData"
        },
        dataSrc: ""
      },
      "lengthMenu": [
        [5, 10, 25, 50, -1],
        [5, 10, 25, 50, "All"]
      ],
    
      language:{
                    "url": "{% static 'language.json' %}",

          },
      columns: [
        {
          "data": 'id',
          className: "middle"
        },

        {
          "data": null,
          className: "middle"
        },
     
     
        {
          "data": 'username',
          className: "text-center middle",

        },
           {
          "data": 'date_joined',
          className: "text-center middle",

        },
          {
          "data": 'date_joined',
          className: "text-center middle",

        },
        {
          "data": 'is_active',
          className: "estado middle",
          render: function (data, type, row) {
            console.log(data);
            if (data) {
              return '<span class="badge badge-success">Habilitado</span> ';
            } else {
              return '<span class="badge badge-danger">Deshabilitado</span> '
            }
          }
        },

        {
          "data": 'estado',
          className: "text-center middle"
        },


      ],
      columnDefs: [{
          targets: [-1],

       render: function (row, data, index) {
            if (index.is_active) {
              var buttons =
                '<a class="btn btn-warning btn-edit-usuario mr-1"  role="button" href="../users/edit/' +
                index.id +
                '"><i class="far fa-edit" ></i></a>' +

                '<button class="btn btn-primary  btn-change-password mr-1 "  role="button" data-id=' + index
                .id +
                '><i class="fas fa-sync-alt"></i></button>' +
                '<button class="btn btn-danger btn-desactivate-usuario "  target="reportes"><i class="fas fa-ban"></i></button>';

              return buttons;
            } else {
              var buttons =
                '<a class="btn btn-warning btn-edit-usuario mr-1"  role="button" href="../users/edit/' +
                index.id +
                '"><i class="far fa-edit" ></i></a>' +

                '<button class="btn btn-primary  btn-change-password mr-1 "  role="button" data-id=' + index
                .id +
                '><i class="fas fa-sync-alt"></i></button>' +
                '<button class="btn btn-success btn-activate-usuario "  target="reportes"><i class="fas fa-play"></i></i></button>';

              return buttons;

            }
       }
        },
        {
          targets: [-3],
          class: 'text-center',
          orderable: false,
          render: function (data, type, row) {
            var html = '';
            $.each(row.groups, function (key, value) {
              html += '<span class="badge badge-success">' + value.name + '</span> ';
            });
            return html;
          }
        },
        {
          targets: [1],
          class: 'text-center',
          render: function (data, type, row) {
            return data.persona
          }
        },


      ],
      "createdRow": function (row, data, index) {
        // if (!data["estado"]) {
        //   $('.btn-success', row).eq(0).removeClass().addClass("btn btn-danger btn-circle")
        //   $(".fa-thumbs-up", row).eq(0).removeClass().addClass("fas fa-thumbs-down")

        // }
      },
        

    })
    $(document).on("click", '.btn-password', function (e) {

      e.preventDefault()
      var tr = TablaUsuarios.cell($(this).closest("td")).index();
      var data = TablaUsuarios.row(tr.row).data();
      de = $.confirm({
        title: "Reestablecer Contraseña",
        content: "URL:../Usuario/reset/" + data.id,
        columnClass: 'col-xl-4 col-lg-4 col-md-8 col-sm-10',
        icon: "fas fa-sync-alt",
        type: "blue",
        scrollToPreviousElement: true,
        scrollToPreviousElementAnimate: true,
        buttons: {
          Confirm: {
            text: 'Guardar cambios',
            btnClass: 'btn btn-primary',

            action: function url(e) {

              this.$content[0].ownerDocument.getElementById("btnEditUser").click()
              return false;
            }
          },

          cancel: function () {

          },
        },



      });


    });
    $(document).on("click", '.btn-change-password', function (e) {
      e.preventDefault()
      var tr = TablaUsuarios.cell($(this).closest("td")).index();
      var data = TablaUsuarios.row(tr.row).data();
      Swal.fire({
        title: 'Reestablecer Contraseña',
        icon: "warning",
        text: "¿Está seguro que desea reestablecer la contraseña?",
        showCancelButton: true,
        confirmButtonColor: "#1cc88a",
        cancelButtonColor: ' #6c757d',
        confirmButtonText: 'Sí, reestablecer!'
      }).then((result) => {
        if (result.isConfirmed) {
          Swal.showLoading()

            fetch("../Usuario/reset/" + data.id + "/", {
              method: "POST",
              headers: {
                'X-CSRFToken': csrftoken
              },
            }).then(data => data.json()).then(response => {
              console.log(response);
              if (response.status = 200) {
                                TablaUsuarios.ajax.reload()

                notificacion(1500, "Genial!", "success", "Contraseña reestablecida")
              } else
              if (response == 404) {
                notificacion(1500, "Error", "error", "Ese usuario no existe")
              }
            })
          
        }
      })
    })
    
    $(document).on("click", '.btn-activate-usuario', function (e) {

      e.preventDefault()
      var tr = TablaUsuarios.cell($(this).closest("td")).index();
      var data = TablaUsuarios.row(tr.row).data();
      Swal.fire({
        title: 'Habilitar usuario',
        icon: "warning",
        text: "¿Está seguro que desea habilitar al usuario?",
        showCancelButton: true,
        confirmButtonColor: "#1cc88a",
        cancelButtonColor: ' #6c757d',
        confirmButtonText: 'Sí, activarlo!'
      }).then((result) => {
        if (result.isConfirmed) {
          Swal.showLoading()

            fetch("../Usuario/activate/" + data.id + "/", {
              method: "POST",
              headers: {
                'X-CSRFToken': csrftoken
              },
            }).then(data => data.json()).then(response => {
              console.log(response);
              if (response.status = 200) {
                TablaUsuarios.ajax.reload()

                notificacion(1500, "Genial!", "success", "Usuario habilitado")
              } else
              if (response == 404) {
                notificacion(1500, "Error", "error", "Ese usuario no existe")
              }
            })
          
        }
      })
    })

      
    $(document).on("click", '.btn-desactivate-usuario', function (e) {

      e.preventDefault()
      var tr = TablaUsuarios.cell($(this).closest("td")).index();
      var data = TablaUsuarios.row(tr.row).data();
      Swal.fire({
        title: 'Inhabilitar usuario',
        icon: "warning",
        text: "¿Está seguro que desea desahibilitar al usuario?",
        showCancelButton: true,
        confirmButtonColor: "#e74a3b",
        cancelButtonColor: '#6c757d',
        confirmButtonText: 'Sí, desactivarlo!'
      }).then((result) => {
        if (result.isConfirmed) {
            Swal.showLoading()

            fetch("../Usuario/desactivate/" + data.id + "/", {
              method: "POST",
              headers: {
                'X-CSRFToken': csrftoken
              },
            }).then(data => data.json()).then(response => {
              if (response.status = 200) {
                notificacion(1500, "Genial!", "success", "Usuario inhabilitado")
                TablaUsuarios.ajax.reload()
              } else
              if (response == 404) {
                notificacion(1500, "Error", "error", "Ese usuario no existe")
              }
            })
          
        }
      })
    })
  });
</script>
{% endblock js_page %}