GeAsis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import ModelTracker
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Web.urls',namespace="Web")),
    path('track/', include('ModelTracker.urls')),
    path('__debug__/', include(debug_toolbar.urls)),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
app_name="Web"

Web/urls.py
from django.urls import include, path

from .views import * 
app_name = 'Web'
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("home", IndexView.as_view(),name="home" ),
    path("", LoginView.as_view(),name="login" ),
    path('logout/',LogoutView.as_view(next_page="/"),name="logout"),
    path('users/',UserListView.as_view(),name="usuarios"),

    path("users/create/",UsuarioCreateView.as_view(),name="create_user"),
    path("users/edit/<int:pk>/",UsuarioUpdateView.as_view(),name="edit_user"),
    path('Usuario/changepassword/<int:pk>/', UsuarioUpdatePasswordView.as_view(), name='UsuarioChangePassword'),
    path('Usuario/reset/<int:pk>/', UsuarioResetPasswordView, name='UsuarioResetPassword'),
    path('Usuario/activate/<int:pk>/', UsuarioActivate, name='UsuarioActivate   '),
    path('Usuario/desactivate/<int:pk>/', UsuarioDesactivate, name='UsuarioDesactivate'),
    path('import/', run, name='inportEESS'),
    path('EESS/', EstablecimientoListView.as_view() ,name='establecimientos'),
    path('programacion/', ProgramacionListView.as_view() ,name='programaciones'),
    path('liquidacion/', LiquidacionListView.as_view() ,name='liquidaciones'),
    path('mantenimiento-variables/', MantenimientoVariablesListView.as_view() ,name='mantenimiento-variables'),
    path('mantenimiento-EESS/', MantenimientoEESSListView.as_view() ,name='mantenimiento-EESS'),
    path('importacion-INFORHUS/', ImportacionBaseListView.as_view() ,name='inforhus')

]

templates/establecimientos.html
{% extends "base.html" %}
 {% block  configuracion %}menu-is-opening menu-open"{% endblock %} 
 {% block establecimientos %}active{% endblock %}
{% comment %} {% block navusuario %}nav-item active{% endblock  %}
{% block collapseUsuarios %}collapse show{% endblock  %}
{% block usuario_list %}collapse-item active{% endblock  %} {% endcomment %}
{% load static %}
{% block content %}


  <div class="card shadow">
    <!-- Card Header - Dropdown -->
    <div class=" card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold ">Listado de Establecimientos</h6>
      <a class="btn btn-primary " href="{% url 'Web:create_user' %}"><i class="fa fa-plus-circle "></i>&nbsp;Nuevo usuario</a>
    </div>
    <!-- Card Body -->
    <div class="card-body ">
<div class="table-responsive">

            <table class="table  table-hover  dt-responsive" id="TablaEESS" style="width: 100%;">
        <thead>
          <tr>
                      <th>Código</th>

            <th>Establecimiento</th>
            <th>Distrito</th>
            <th >Provincia</th>
            <th >Departamento</th>
            <th>Responsble</th>
            <th>Opciones</th>
          </tr>
        </thead>



      </table>
      </div>
    </div>
  </div>

{% endblock content %}
{% block js_page %}

<script>
 var TablaUsuarios
  $(document).ready(function () {

    TablaUsuarios = $("#TablaEESS").DataTable({
      responsive: true,
      processing:true,
      ordering:false,
      ajax: {
        url: "{% url 'Web:establecimientos' %}",
        type: "POST",
        data: {
          "action": "searchData"
        },
        dataSrc: ""
      },
      "lengthMenu": [
        [5, 10, 25, 50, -1],
        [5, 10, 25, 50, "All"]
      ],
    
      language:{
                    "url": "{% static 'language.json' %}",

          },
      columns: [
      {
          "data": 'codigo',
          className: "middle"
        },
        {
          "data": 'descripcion',
          className: "middle"
        },

        {
          "data": "distrito",
          className: "middle"
        },
     
     
        {
          "data": 'provincia',
          className: "text-center middle",

        },
     
     {
          "data": 'departamento',
          className: "text-center middle",

        },
     
     {
          "data": 'responsable',
          className: "text-center middle",

        },
     
   {
          "data": null,
          className: "text-center middle",

        },
      ],
      columnDefs: [{
          targets: [-1],

       render: function (row, data, index) {
              var buttons =
                '<a class="btn btn-warning btn-edit-usuario mr-1"  role="button" href="../users/edit/' +
                index.id +
                '"><i class="far fa-edit" ></i></a>' ;

              return buttons;
             
       }
        },



      ],
      "createdRow": function (row, data, index) {
        // if (!data["estado"]) {
        //   $('.btn-success', row).eq(0).removeClass().addClass("btn btn-danger btn-circle")
        //   $(".fa-thumbs-up", row).eq(0).removeClass().addClass("fas fa-thumbs-down")

        // }
      },
        

    })


  });
</script>
{% endblock js_page %}

templates/importacionBase.html
{% extends "base.html" %}
 {% block  mantenimiento %}menu-is-opening menu-open{% endblock %} 
 {% block rrhh %}menu-is-opening menu-open{% endblock %}
 {% block base %}active{% endblock %}

{% load static %}
{% block content %}
<h1>Importación de la Base INFORHUS</h1>

{% endblock %}

templates/liquidacion.html
{% extends "base.html" %}
 {% block  ingreso %}menu-is-opening menu-open{% endblock %} 
 {% block liquidacion %}active{% endblock %}

{% load static %}
{% block content %}
<h1>Liquidación</h1>

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>GeAsis| Login</title>
  {% load static %}
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'css/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="../../index2.html">GeAsis</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Iniciar Sesión</p>

      <form id="formlogin" method="POST">
      {% csrf_token %}

     <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Usuario" name="username"  id="id_username">  
                
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
<input class="form-control" placeholder="Contraseña" type="password" name="password" required id="id_password">     
     <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="button" id="boton" class="btn btn-primary btn-block">Ingresar</button>
          </div>
          <!-- /.col -->
        </div> 
      </form>

     
      <!-- /.social-auth-links -->

      <p class="mb-1">
        <a href="forgot-password.html">Olvidé mi contraseña</a>
      </p>
      {% comment %} <p class="mb-0">
        <a href="register.html" class="text-center">Register a new membership</a>
      </p> {% endcomment %}
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.js" ></script>     
  <script src="{% static 'js/sweetalert2.min.js' %}"></script>

<!-- Bootstrap 4 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>
  <script>
  document.addEventListener("keyup", function(event) {
  // Number 13 is the "Enter" key on the keyboard
  if (event.keyCode === 13) {
    // Cancel the default action, if needed
    event.preventDefault();
    // Trigger the button element with a click
    document.getElementById("boton").click();
  }
});
  document.getElementById("boton").addEventListener("click",function(){
    let form = document.getElementById("formlogin")
    let formData = new FormData(form)
    fetch("{% url 'Web:login' %}",{
      method:"POST",
      body: formData

    }).then(data=>data.json()).then(response=>{
      console.log(response);
      if(response.status==500){
        if(response.error.username  && response.error.password ){
          notificacion(4000,"","error","Ingrese sus credenciales!.")

        }
        else
          if(response.error.username){
          notificacion(4000,"","error","El campo usuario es obligatorio.")

        }
        else
         if(response.error.password){
          notificacion(4000,"","error","El campo contraseña es obligatorio.")

        }
        else
        if(response.error.__all__){
          notificacion(4000,"","error",response.error.__all__[0])

        }
      document.getElementById("id_password").value=""
      }else{
        window.location.href="{% url 'Web:home' %}"
      }
    })

  })
    const notificacion = (time, title, type, message) => {
    
      const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: time,
  timerProgressBar: true,
  didOpen: (toast) => {
    toast.addEventListener('mouseenter', Swal.stopTimer)
    toast.addEventListener('mouseleave', Swal.resumeTimer)
  }
})

Toast.fire({
  icon: 'error',
  title: message
})
    } 
  </script>
</body>
</html>

templates/mantenimientoEESS.html
{% extends "base.html" %}
 {% block  mantenimiento %}menu-is-opening menu-open{% endblock %} 
 {% block EESS %}active{% endblock %}

{% load static %}
{% block content %}
<h1>Mantenimiento de Establecimientos de Salud</h1>

{% endblock %}

templates/mantenimientoVariables.html
{% extends "base.html" %}
 {% block  mantenimiento %}menu-is-opening menu-open{% endblock %} 
 {% block variables %}active{% endblock %}

{% load static %}
{% block content %}
<h1>Mantenimiento de Variables de Liquidacion y Programación</h1> 

{% endblock %}

templates/programacion.html
{% extends "base.html" %}
 {% block  ingreso %}menu-is-opening menu-open{% endblock %} 
 {% block programacion %}active{% endblock %}

{% load static %}
{% block content %}
<h1>Programación</h1>

{% endblock %}